stages:
  stage_01:
    cmd: python3 stage_01.py
    deps:
      - stage_01.py
    outs:
      - artifacts_01.txt
    
  stage_02:
    cmd: python3 stage_02.py
    deps:
      - stage_01.py
      - stage_02.py
      - artifacts_01.txt

  stage_03:
    cmd: python3 stage_03.py
    deps:
      - stage_01.py
      - stage_03.py
      - artifacts_01.txt
    outs:
      - artifacts_02.txt

  stage_04:
    cmd: python3 stage_04.py
    deps:
      - stage_01.py
      - stage_03.py
      - stage_04.py
      - artifacts_01.txt
      - artifacts_02.txt


  